# Generated by Django 4.1.7 on 2026-01-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0004_alter_activity_id_alter_leaderboard_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
